### ISSUE TITLE
[Feature request] allow case insensitive search

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#211]
*On GitLab by @Akuseru on Jul 20, 2020, 01:47*

---

**Comment by jdujava** [comment]
Case insensitive search is the default (and currently the only option), right?

**Comment by alerque** [comment]
The search is indeed case sensitive, but it is not locale-aware case sensitive. This is not a problem for many language, but it does make it nearly impossible to do case insensitive searches is Turkish or Azeri documents. A locale aware case casting solution would be welcome. Should I open that as a separate tracking issue?

**Comment by sebastinas** [comment]
Please create a new one as this is an import of the gitlab instance without much context.
