### ISSUE TITLE
[Feature request] Single-click for mouse setting

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#212]
*On GitLab by @oshd on Jul 23, 2020, 03:50*

---

It would be good to have the ability to set the mouse to be single click (e.g., follow a link after a single click).

**Comment by sebastinas** [comment]
*On GitLab by @itaranto on Jan 30, 2024, 20:32*

---

This would be really nice.

**Comment by jdujava** [comment]
Already implemented via `double-click-follow` setting, right?
