### ISSUE TITLE
Files whose name starts with letters followed by a colon don’t open via dbus

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#215]
*On GitLab by @vejkse on Aug 7, 2020, 06:12*

---

If I try through D-Bus to open files whose name starts with one or more [a-zA-Z] immediately followed by a colon, I get the following error message: “Could not read file from GIO and copy it to a temporary file.”  There is no problem if there is at least a space, a number or a Greek letter before the colon.

This is not a new problem, it dates back to a few years.

Here’s a minimal Python script to reproduce the problem, using dbus-python:
```python
#!/bin/python3

import dbus
import subprocess
import time

zathuraPopen = subprocess.Popen(['zathura', '--log-level=debug'])
zathuraName = 'org.pwmt.zathura.PID-' + str(zathuraPopen.pid)
time.sleep(1.0)

zathuraObject = dbus.SessionBus().get_object(zathuraName, '/org/pwmt/zathura')
zathuraDBus = dbus.Interface(zathuraObject, 'org.pwmt.zathura')

zathuraDBus.OpenDocument("1:b.pdf", '', 1)
time.sleep(5.0)
zathuraDBus.OpenDocument("a:b.pdf", '', 1)
time.sleep(5.0)
zathuraDBus.OpenDocument("x:b.pdf", '', 1)
```

Executed in a directory where the first two files exist (and are identical), whereas the third doesn’t, for both the existing `a:b.pdf` and the nonexisting `x:b.pdf` I get the error message quoted above as well as the following messages in the terminal:
```
debug: ../zathura/dbus-interface.c:392: handle_method_call(): Handling call 'org.pwmt.zathura.OpenDocument' on '/org/pwmt/zathura'.
error: Can not copy to temporary file: Operation not supported
```

**Comment by sebastinas** [comment]
That's a known limitation when having colons in file names. Use `file://...` in that case.

**Comment by sebastinas** [comment]
closed

**Comment by sebastinas** [comment]
*On GitLab by @vejkse on Aug 7, 2020, 10:26*

---

Thank you! I didn’t find any other mention of that issue.  It seems that just using the full path of the file is enough to avoid the problem.

**Comment by hervyqa** [comment]
I have some pdf files like this:

```
Cassandra: The Definitive Guide, (Revised) Third Edition: Distributed Data at Web Scale.pdf
Prometheus: Up & Running: Infrastructure and Application Performance Monitoring.pdf
Terraform: Up and Running: Writing Infrastructure as Code.pdf
```

the files cannot be opened.

but, if the period (:) in the first word is deleted (or change to dash (-)) then the pdf can be opened.

```
Cassandra - The Definitive Guide, (Revised) Third Edition: Distributed Data at Web Scale.pdf
Prometheus - Up & Running: Infrastructure and Application Performance Monitoring.pdf
Terraform - Up and Running: Writing Infrastructure as Code.pdf
```

**Comment by sebastinas** [comment]
Use `file://...` URIs in this case
