### ISSUE TITLE
[Feature request] Touch zoom

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#287]
*On GitLab by @s.lawrence on Aug 11, 2021, 23:54*

---

When using zathura on a touchscreen, I would expect a pinch movement (two fingers expanding or contracting) to cause the document to zoom. Instead, it selects a region (determined entirely by one of the two fingers).

I think zoom is better for a few reasons.

*  I, personally, want to zoom much more than I want to select. (This is the real reason, obviously.)
*  Firefox zooms with a pinch movement! That means it must be right.
*  When a 2-in-1 laptop/tablet is folded, the keyboard is inaccessible. This makes selecting something mostly useless, because I'm in viewing mode, not writing mode. However, zooming is very useful --- and without keyboard interaction, there's currently no way to zoom (without unfolding the laptop to access the keyboard).

**Comment by sebastinas** [comment]
mentioned in commit fb3831b3fad38b1ff5adac406429ca79c6ad4056

**Comment by sebastinas** [comment]
*On GitLab by @JM9 on Feb 16, 2024, 22:44*

---

I see this issue is closed and commits made. However, I'm not able to trigger zoom using touch and latest zathura and girara sources. What is the zoom gesture that is supposed to work? Is it a two finger pinch-to-zoom or something else?

**Comment by snonux** [comment]
Seems to work for me when I use a 3-finger gesture on a touch screen. E.g.:

* With one finger (e.g. left hand) touch and hold the screen
* With two other fingers (e.g. right hand) pinch and zoom.
* I can release the left hand finger while pinching-and-zooming.
