### ISSUE TITLE
Print recolored version of PDF

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#294]
*On GitLab by @kying on Oct 26, 2021, 20:18*

---

I really like the way that zathura recolor the pdfs to dark mode, while preserving the colors that looks natural in dark background. I'm wondering if there is way to export/save/print this recolored version of PDF?

**Comment by sebastinas** [comment]
This is currently out of scope.

**Comment by alerque** [comment]
As it should be! Use a PDF/PostScript stream editor to modify the source document if this is a real need. It's not trivial to do and will inevitably cause lots of edge case trouble (not to mention the edges of pages. A screen viewer doesn't face half the issues that it would be to send a filtered document to a printer.
