### ISSUE TITLE
zathura crahsed when openning epub in Double Page View

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#305]
*On GitLab by @prehonor on Jan 19, 2022, 15:39*

---

*** longjmp causes uninitialized stack frame ***: terminated
Segmentation fault
![Peek_2022-01-19_22-37](https://git.pwmt.org/pwmt/zathura/uploads/cdc1ee6a17575bf416fd9e2fa5abd63d/Peek_2022-01-19_22-37.gif)

**Comment by sebastinas** [comment]
Please provide a backtrace of the crash.

**Comment by sebastinas** [comment]
*On GitLab by @Galicarnax on Mar 13, 2023, 07:25*

---

Recently, I also observe this bug. It happens randomly when I'm navigating over a document (either with mouse, or with page up/down). When launching from terminal, I can see this when Zathura crashes:
```
*** longjmp causes uninitialized stack frame ***: terminated
zsh: IOT instruction  zathura 
```
I'm on Arch Linux, zathura version 0.5.2.

**Comment by sebastinas** [comment]
*On GitLab by @Galicarnax on Jan 9, 2024, 06:40*

---

With version 0.5.4, this bug still happens for some PDFs. For concreteness, I will show `gdb` output for this PDF: https://arxiv.org/abs/2401.03518v1

```plaintext
(gdb) run ~/Downloads/2401.03518.pdf 
Starting program: /usr/bin/zathura ~/Downloads/2401.03518.pdf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff31ff6c0 (LWP 1003223)]
[Thread 0x7ffff31ff6c0 (LWP 1003223) exited]
[New Thread 0x7ffff31ff6c0 (LWP 1003224)]
[New Thread 0x7ffff29fe6c0 (LWP 1003225)]
[Thread 0x7ffff31ff6c0 (LWP 1003224) exited]
[Thread 0x7ffff29fe6c0 (LWP 1003225) exited]
[New Thread 0x7ffff29fe6c0 (LWP 1003226)]
[New Thread 0x7ffff31ff6c0 (LWP 1003227)]
[New Thread 0x7fffe7a476c0 (LWP 1003228)]
[New Thread 0x7fffe72466c0 (LWP 1003229)]
[New Thread 0x7fffe6a456c0 (LWP 1003230)]
[Thread 0x7fffe72466c0 (LWP 1003229) exited]
[Thread 0x7fffe6a456c0 (LWP 1003230) exited]
Error while mapping shared library sections:
/proc/1003217/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/1003217/ns/mnt: Permission denied.
[New Thread 0x7fffe6a456c0 (LWP 1003238)]
[New Thread 0x7fffe72466c0 (LWP 1003241)]

Thread 11 "pool-org.pwmt.z" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe72466c0 (LWP 1003241)]
0x000000000000000b in ?? ()
(gdb) bt
#0  0x000000000000000b in  ()
#1  0x0000000000000000 in  ()
```
I'm not sure if that's helpful. I can test with some other ways, if you ask.

**Comment by sebastinas** [comment]
@Galicarnax I can no longer reproduce the issue with mupdf 1.24.x. Please reopen if it is still an issue.

**Comment by Galicarnax** [comment]
Yes, with version 0.5.6 I also cannot reproduce the issue with the same PDF file. No crashes while navigating.
