### ISSUE TITLE
Quickmarks not preserved

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#308]
*On GitLab by @polirritmico on Jan 26, 2022, 18:07*

---

# Summary:
Zathura doesn't preserve the quickmarks added to a document when reopening the same file.

# Steps to reproduce:
1. `$ zathura file.pdf`
2. Create a quickmark: `mt`
3. Close Zathura `:quit`
4. Reopen the file: `$ zathura file.pdf`
5. Going to the quickmark with `'t` doesn't work

# Expected behavior
All quickmarks created in the file on previous sessions should work.

# System info:
* zathura 0.4.8
* girara 0.3.6 (runtime: 0.3.6)
* (plugin) cb (0.1.8) (/usr/lib64/zathura/libcb.so)
* (plugin) pdf-mupdf (0.3.7) (/usr/lib64/zathura/libpdf-mupdf.so)
* Operating System: Gentoo Linux
* Kernel Version: 5.15.16-gentoo (64-bit)
* Graphics Platform: X11

---

Thanks for this really good software!

**Comment by sebastinas** [comment]
*On GitLab by @epicalyx on May 7, 2023, 11:04*

---

I use Zathura with LaTeX to continuously reload the pdf file after the tex file is recompiled. Since the quickmarks are lost on reloading, it's not feasible to use them in this situation. I find quickmarks extremely useful and it would help my workflow to preserve them after reloading.

**Comment by sebastinas** [comment]
*On GitLab by @jdujava on May 7, 2023, 16:09*

---

Also preserving the last search word/phrase would be amazing.

**Comment by sh-cau** [comment]
I second this. Otherwise quickmarks are useless.

**Comment by Evidlo** [comment]
Just wanted to point out that if you have two copies of a document open, the last instance of Zathura closed will overwrite all the quickmarks on the document.

Not necessarily a bug, but just an idiosyncrasy to be aware of.
