### ISSUE TITLE
require dbus for synctex work

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#311]
*On GitLab by @to on Feb 11, 2022, 11:38*

---

On Void Linux, if I have dbus installed, synctex works fine.
If I remove it, I get
```
$ zathura -x "/usr/bin/vim-x11 -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:2:'/home/nicolo/Documents/drafts/Gamme/main.tex'  '/home/nicolo/Documents/drafts/Gamme/main.pdf'&
[1] 2576
$ error: Could not connect to session bus: Error spawning command line “dbus-launch --autolaunch=7818fdfca1741e84e1d89d015f666154 --binary-syntax --close-stderr”: Child process exited with code 1
error: Got no usable data from SyncTeX or D-Bus failed in some way.
```
Is dbus required for such functionality to work?
see also #251 

I believed that libsynctex would be enough, so zathura speaks to synctex directly, not through dbus: is this false?

Thanks.

**Comment by sebastinas** [comment]
Yes, dbus is required for synctex support to work. `zathura --synctex-forward` essentially translates the commands to some dbus message that is then handled by the zathura instance that has the corresponding document open.

**Comment by sebastinas** [comment]
closed

**Comment by sebastinas** [comment]
*On GitLab by @to on Apr 22, 2022, 19:02*

---

Thanks for clarifying. Do you see any way to do synctex without dbus?

**Comment by sebastinas** [comment]
Sure, we could invent a custom RPC protocol - but I don't think that's worth the effort (both in implementing and maintaining it).

**Comment by dirichy** [comment]
Could we add a command in zathura like ":synctex line:column" so that we can combine this with some automate app like xdotool on linux or hammerspoon on macos to let synctex work? 
Until now dbus on macos is difficult to run.
