### ISSUE TITLE
Prevent flickering when reloading document

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#312]
*On GitLab by @frabjous on Mar 8, 2022, 03:22*

---

![zathura-flicker-withtext](https://git.pwmt.org/pwmt/zathura/uploads/7c1b33ad598aedf72af464eaef021022/zathura-flicker-withtext.mp4)

The issue is illustrated in the attached video file. It shows the difference between `llpp` and `zathura` when a file is reloaded over and over.

I like to use a live-updating PDF preview when I write. I do this with LaTeX and markdown files. I have my text editor set up to automatically save the file and process it with the appropriate tool to create a PDF. Zathura is nice because it reloads changes as soon as they happen. But unlike some other PDF viewers (llpp, barebones mupdf), Zathura flickers/flashes when it reloads, which is very distracting when you reload the same document over and over while you're writing.

You can see the difference between Zathura and llpp in the attached video. 

Not sure how hard this would be to bring about, but since llpp has done it, hopefully you can consider doing so as well.

Full disclosure: I was one of the people who convinced the devs of llpp to make it work well in the first place. (see [this issue](https://github.com/moosotc/llpp/issues/12) on its GitHub). But I am thinking of switching to Zathura because I'd like something that runs natively on wayland.

**Comment by sebastinas** [comment]
*On GitLab by @Alex-Muirhead on Mar 28, 2023, 08:51*

---

Did you find any fix for this @frabjous? I've got the same use-case and issue, and it's quite disruptive.

**Comment by sebastinas** [comment]
*On GitLab by @frabjous on Mar 28, 2023, 15:56*

---

I'm using Sioyek now, which is better with regard to flickering, though still not as good as llpp.

**Comment by sebastinas** [comment]
mentioned in commit c11ba01cfbdc57f9d3a61585520ae1ac8c9c4fd3

**Comment by frabjous** [comment]
> _On GitLab by @frabjous on Mar 28, 2023, 15:56_
> 
> I'm using Sioyek now, which is better with regard to flickering, though still not as good as llpp.

It's always nice when people answer their own questions. 😃
