### ISSUE TITLE
System freeze (for a few seconds) when exiting with :q

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#345]
*On GitLab by @gi1242 on Aug 13, 2022, 23:07*

---

When viewing a file type `:q` to exit. My system (Plasma/Wayland) freezes for about 20 seconds before zathura exits.

Here's my system info:

```
Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.15.60-1-lts (64-bit)
Graphics Platform: Wayland

Zathura 0.4.9-1, girara 0.3.7-1, gtk-3.24.34-1
```

Thanks in advance:

**Comment by sebastinas** [comment]
*On GitLab by @valoq on Aug 21, 2022, 15:13*

---

This seems to be an issue with KDE/Qt or your particular setup.

@gi1242 
Can you test this on weston to make sure this is the case?

And please also try the newest git version of zathura if possible.

**Comment by sebastinas** [comment]
*On GitLab by @gi1242 on Apr 2, 2023, 20:51*

---

When I checked with the most recent version (0.5.2) it seems to not be present anymore. Maybe it was a Kde/QT issue. Regardless, it's gone now:

    Operating System: Arch Linux 
    KDE Plasma Version: 5.27.3
    KDE Frameworks Version: 5.104.0
    Qt Version: 5.15.8
    Kernel Version: 6.2.9-arch1-1 (64-bit)
    Graphics Platform: Wayland

**Comment by gi1242** [comment]
I definitely still see the issue:

    Operating System: Arch Linux 
    KDE Plasma Version: 6.0.4
    KDE Frameworks Version: 6.1.0
    Qt Version: 6.7.0
    Kernel Version: 6.6.29-1-lts (64-bit)
    Graphics Platform: Wayland

The issue is only present when Zathura is run under wayland (not xwayland); I run xeyes and make sure the mouse cursor doesn't move when the mouse is over the Zathura window.

After this run from a terminal

    zathura --synctex-forward "50:1:file.tex" file.pdf

The first run opens a new window and focusses it. All subsequent runs just highlight the line in question without focussing anything.
