### ISSUE TITLE
Segmentation Fault when accessing the Table of Contents/Bookmarks

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#388]
*On GitLab by @kamsh on Mar 22, 2023, 16:30*

---

When I press TAB I am expecting to see the Table of Contents, but what happens is that the program crashes and prints `Segmentation fault`. This started happening after I updated my system recently using `pacman -Syyu`.

[backtrace](https://pastebin.com/bgN9yQmJ)

I got the backtrace using [this method](https://wiki.ubuntu.com/Backtrace). If there is anything else I should do please tell me.

**Comment by sebastinas** [comment]
*On GitLab by @kamsh on Mar 22, 2023, 16:40*

---

After looking at the backtrace I figured I would update girara, and it looks like that was the problem. Updating girara from 0.3.9 to 0.4.0 solved it, and apparently it was possible related to [this issue](#17)

**Comment by MaMiMa81** [comment]
Good Afternoon @sebastinas
Like yourself I too have issues with later versions of zathura (with associated girara & zathura-pdf-poppler) with tabbed.

I use tabbed through the preview-tabbed plugin in nnn file manager & posted an issue on their github project:

[https://github.com/jarun/nnn/issues/1793#issue-2061596187](url)


I am still using zathura v. 0.5.2 with girara v. 0.4.0 & zathura-pdf-poppler v. 0.3.1 but was wondering if you had any joy debugging:

[https://github.com/pwmt/zathura/issues/456#issue-2272341982](url)
