### ISSUE TITLE
how to navigate through chapters

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#402]
*On GitLab by @asklow on Jul 3, 2023, 08:28*

---

how to navigate through chapters ? I've tried all the keyboard shortcuts. None worked.

**Comment by sebastinas** [comment]
*On GitLab by @marcoe on Jul 6, 2023, 12:25*

---

Have you tried `Tab` to enter index mode? Maybe the document doesn't have any chapter/index information.

**Comment by sebastinas** [comment]
*On GitLab by @asklow on Jul 6, 2023, 16:51*

---

Oh. Haven't tested `tab`. Works now. I'm new to zathura. Read the manual, but no mention of chapters access. Can you update the manual with this info ? Tq.

**Comment by kllmanu** [comment]
@sebastinas I'd love to be able to navigate to the prev/next chapter with a keyboard shortcut instead of hitting `tab` key all the time.
