### ISSUE TITLE
PDF document with multiple orientation is not displayed correctly

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#446]
*On GitLab by @lamurian on Jan 31, 2024, 01:18*

---

Using the latest update in void Linux x86_64, Zathura does not correctly display PDF documents with multiple orientations. Previously, Zathura could render PDF documents containing landscape and portrait pages. Zathura version:

```
zathura 0.5.4
girara 0.4.2 (runtime: 0.4.2)
(plugin) pdf-mupdf (0.4.1) (/usr/lib64/zathura/libpdf-mupdf.so)
```

I also found the same problem reported in StackExchange: https://unix.stackexchange.com/questions/767032/in-zathura-is-it-possible-to-correctly-show-a-pdf-with-mixed-page-orientation?newreg=18c552a230a248d68eeaf0b1e0586c9d

Document example: https://ufile.io/fw9nqnq2 (the link will expire on 01 March 2024)

Screenshot when viewed in Zathura:

![Viewed in Zathura](https://i.ibb.co/GnscDp3/2024-01-31-001913-401x1020-scrot.png)

Screenshot when viewed in Chromium:

![Viewed in Chromium](https://i.ibb.co/ynQSy4t/2024-01-31-011731-1111x974-scrot.png)

Is there any workaround to this issue?

**Comment by sebastinas** [comment]
*On GitLab by @lamurian on Jan 31, 2024, 01:31*

---

Seems like related to:
- #383 
- #39
- #41

**Comment by einhander** [comment]
The same on debian testing. But according to https://www.linux.org.ru/forum/desktop/17534248 it ok on other distro.

**Comment by sebastinas** [comment]
Duplicate of #436.
