### ISSUE TITLE
Add source command - [merged]

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#509]
*On GitLab by @tjf on Nov 23, 2021, 03:20*

---

_Merges sourcecmd -> develop_

Adds a `source` command to reload or load new config file without restarting zathura. Takes one optional argument, a directory, otherwise the current config directory is implied.

Implements a feature requested in issue #186.

**Comment by sebastinas** [comment]
merged

**Comment by sebastinas** [comment]
mentioned in commit 01ee79eeab3a5dd23afc6137f7ec6c6c9249c0e4

**Comment by ashley-paul-12345** [comment]
Hi, can this add as a function so we can map it to a key?
