### ISSUE TITLE
Searching in index

### ISSUE THREAD

**Issue by jdujava** [pwmt/zathura#565]
It would be awesome to have search functionality similar to `/` available in the index.

By accident I sometimes make a "doubleclick" `<Mouse3>` in the index, after which typing seems to trigger some kind of "search" functionality. Seems kinda strange, since it isn't documented, coudn't find any further information, and also works only if the given index entry starts with the given search prompt.

Seems to me like a useful thing to have, maybe even some kind of fuzzy matching would be sometimes desirable.

**Comment by shunlog** [comment]
Can confirm, there is such a feature. Looks like after `<Mouse3>`, all the key-strokes act on the input panel in the bottom right, and you can search for index entries, but only if they're visible. And then it disappears after 5 seconds.

I think this feature is necessary.

 ![image](https://github.com/pwmt/zathura/assets/48106195/f14456c7-cf47-4a99-b061-c189821f7dcf)

**Comment by laomuon** [comment]
Not just `<Mouse3>` but double click `<Mouse2>` or anything that can bring the index in focus also works. After the first time, every shortcut that we set for the index will not work, as the key inputs will be all funnel to the search. This is the `interactive_search` feature of `GtkTreeView`.

To properly implement this feature, we can:
- Use the native API of Gtk. This is, I think, the easiest way to have something that functions, but have a drawback of not easily extend. As in the screenshot of @shunlog , the search dialog is not in the same theme as the rest of application. Also, it comes with all the limits of Gtk (not able to search outside of visible window, will be deprecated in `4.10`,...)
- Make something of our own, attach to `girara` like what we did with search in documents. This way, we can have more control but requires more works to be done.

What do you think @sebastinas ?

**Comment by sebastinas** [comment]
This could re-use the existing integration for the search command, but no idea how much work that is.

**Comment by tuurep** [comment]
Hi, shouldn't this issue still be open?
