### ISSUE TITLE
Horizontal Scrolling support

### ISSUE THREAD

**Issue by Mash-em** [pwmt/zathura#572]
It would be nice to have option of Horizontal scrolling like in firefox browser.

**Comment by alerque** [comment]
Zathura has horizontal scrolling. It works fine for me from keyboard bindings, from my horizontal scroll wheel on a mouse, and using <kbd>Shift</kbd> with the regular scroll wheel. What exactly are you missing?

**Comment by Mash-em** [comment]
holding shift does nothing for me , all the pages of document are aligned vertically , if they could be aligned horizontally and scrolled that way.

**Comment by alerque** [comment]
```
:set pages-per-row N
```

Where N is the length of your document.

**Comment by Mash-em** [comment]
how to revert this
