### ISSUE TITLE
An option to switch `[current_page / total_pages]` to just `total_pages`

### ISSUE THREAD

**Issue by Orest58008** [pwmt/zathura#590]
zathura-poppler (and now zathura-mupdf) seemingly provide total pages count as (current_page/total_pages) so the statusbar usually displays something like `[33 / (33/273)]`.

I'm using Arch Linux with the following versions of software:
```
info: Opening plain database via sqlite backend.
warning: sqlite database already exists. Set your database backend to sqlite
zathura 0.5.6
girara 0.4.4 (runtime: 0.4.4)
(plugin) djvu (0.2.9) (/usr/lib/zathura/libdjvu.so)
(plugin) pdf-mupdf (0.4.2) (/usr/lib/zathura/libpdf-mupdf.so)
```

**Comment by sebastinas** [comment]
There is an argument to be made that if the page label is the same as the page number, that it should not be displayed.

**Comment by VishnuSanal** [comment]
hi, I would like to work on this issue.
