### ISSUE TITLE
longjmp causes uninitialized stack frame

### ISSUE THREAD

**Issue by paulusel** [pwmt/zathura#594]
Zathura crashes with the following terminal log.

```
*** longjmp causes uninitialized stack frame ***: terminated
Aborted (core dumped)
```

This happens during navigation. Pressing Space(next page) for a while, for example causes this this crash.

OS: Arch
Zathura: 5.6-2
Installed: From arch repositories
 Display: Hyprland (wayland)

**Comment by sebastinas** [comment]
You need to upgrade zathura-pdf-mupdf to 0.4.3.
