### ISSUE TITLE
zathura uses deprecated backend and warns about it

### ISSUE THREAD

**Issue by mjg** [pwmt/zathura#600]
With zathura 0.5.6, without preexisting config nor databases, the following happens:

On first run with a pdf:
```
info: Opening plain database via sqlite backend.
info: Database migration done. Set your database backend to sqlite.
```
Note that there was no database to convert. The run results in `~/.local/share/zathura/bookmarks.sqlite` being created (no plain file database).
In the second run with a pdf:
```
info: Opening plain database via sqlite backend.
warning: sqlite database already exists. Set your database backend to sqlite
````
Note that there still is no plain database at all.

It is quite unfortunate that even new users are confronted with migration notices, and that in general the non-existence of plain databases does not shut up the warning. Consequently, even after migrating to sqlite and deleting the plain ones, the warning still pops up.

I know I can avoid the warning by editing `zathurarc`, but that is not a great user experience.

Also, it's only bookmarks which are being migrated, not history, it seems.

**Comment by sebastinas** [comment]
History should also be migrated. If it is not, this is a separate bug.
