### ISSUE TITLE
Segfault while scrolling or zooming

### ISSUE THREAD

**Issue by mihalyvaghy** [pwmt/zathura#601]
Environment: i3wm on Manjaro Linux, zathura 0.5.6, pdf-mupdf 0.4.2

Faster scrolling or zooming seems to lead to more frequent crashes, but the issue is still present when I scroll/zoom very slowly and carefully. Crashes are more frequent if the pdf contains small images of size small ~200KB, but still present if the pdf doesn't contain a single image. I have been able to consistently reproduce the error for small file sizes and short (even single page) pdfs. Problem persists after reinstalling with pacman or compiling from source. Running with debug logs either leads to a blank segfault or the following error:
*** longjmp causes uninitialized stack frame ***: terminated

The scrolling issue only seems to arise using a mouse or a touchpad, but zooming also crashes with default keybindings. On previous versions of zathura I very rarely encountered this problem if the pdf contained many images, but the new version is basically unusable.

**Comment by sebastinas** [comment]
You need to upgrade to zathura-pdf-mupdf 0.4.3.
