### ISSUE TITLE
Conflicting code causes zathura to crop oversized pdf pages

### ISSUE THREAD

**Issue by malmerri42** [pwmt/zathura#608]
From issue #602, I forked the development branch and inspected cell_width and cell_height which are part of the document struct defined here:
https://github.com/pwmt/zathura/blob/c3ffe3e02fc65be6de92dfc25a7f77e42c0b4e0e/zathura/document.c#L37-L38

Placing a watchpoint after the document has been created on cell_width and cell_height shows that initially this code:
https://github.com/pwmt/zathura/blob/c3ffe3e02fc65be6de92dfc25a7f77e42c0b4e0e/zathura/adjustment.c#L16-L24
sets the cell_width and cell_height to the dimensions of the largest page in the document. 

Later down the line the following code overwrites the above adjustments to cell_width and cell_height:
https://github.com/pwmt/zathura/blob/c3ffe3e02fc65be6de92dfc25a7f77e42c0b4e0e/zathura/zathura.c#L1114-L1118
It seems like it sets the cell_width and cell_height to the most frequent page width and height.
If you comment out the above code, zathura will correctly show oversized pdf pages.

**Comment by sebastinas** [comment]
Fixed in 9c0017b.
