### ISSUE TITLE
Centering of current index row is wrong on the first index toggle

### ISSUE THREAD

**Issue by jdujava** [pwmt/zathura#615]
Toggling index chooses index row corresponding to the current page, and centers it in the index view.

However, on the first opening of the index, the current index row is top aligned (it is necesarry to have long enough index to notice such behavior). Afterwards, the centering works fine.

I have no idea why this happens, any pointers would be welcome.

**Comment by laomuon** [comment]
Currently working into this, I suspect there is some race conditions in the `Gtk` event loop, where the first scroll may be called before the widget is finished drawing, leading to weird results, whereas in the subsequent calls, the widget is already fully drawn so there is no issue

**Comment by laomuon** [comment]
Ok I narrow down the problem! It seems like in `Gtk`, when add a new item to the tree, the size is not updated immediately, so the function `gtk_tree_view_scroll_to_cell` cannot align the item correctly. If you dont mind @jdujava I'd like to take this issue

**Comment by jdujava** [comment]
@laomuon Certainly, I would be glad!

**Comment by laomuon** [comment]
@jdujava It seems that you are the one who worked the most in this part of code recently, so can you take a look at my PR and test it to see if the behavior meets your expectation?
