### ISSUE TITLE
wish can dump epub to pdf

### ISSUE THREAD

**Issue by vincentaxhe** [pwmt/zathura#631]
the epub display is good, I wish can save it to pdf. better than convert by calibre.

**Comment by alerque** [comment]
There are many even better tools for that job. Typesetting is a complex task and yes the Calibre code for this is rudimentary at best. Adding this to Zathura would be a waste of developer time. I suggest using Pandoc with one of thee various PDF output drivers — whichever ones styling customization suites you best.
