### ISSUE TITLE
recent file list does not update

### ISSUE THREAD

**Issue by WQingkun** [pwmt/zathura#632]
Open a file in terminal with command `zathura /path/to/file` or use `:open /path/to/file`  inside zathura does not add new entry in recent file list. It does not change the next time running `:open <Tab>` . My recent file list is not empty by the way. I would like to know if it's a bug or it's due to my config. Thanks!

**Comment by WQingkun** [comment]
Seems the logic is  when type `:open /mnt/ <tab>`, recent file's path beginning with `/mnt/` will appear. If one type `:open <Tab>`, only history of working directory will be considered. So when I launch zathura from home directory, I will not see file from `/mnt/` opened last time.

**Comment by sebastinas** [comment]
That behavior is consistent with vim, so working is intended.
