### ISSUE TITLE
2-page spreads only render half

### ISSUE THREAD

**Issue by TimovVeen** [pwmt/zathura#652]
I've tried this plugin on some .cbz manga files. Occasionally there is a double page spread, which is represented as one page/image. However, in Zathura the right half of the spread is cut off and only the left page is rendered.

This issue has occurred on 4 files I've tested in both single and double page mode. I've confirmed they render correctly when opened in another application.

Intended full image:
![pagespread](https://github.com/user-attachments/assets/2f96364f-a27f-45d6-835f-7fe34e12867d)

Right page cropped in reader:
![cropped](https://github.com/user-attachments/assets/9173fe21-f4e0-4f8e-b6c4-546ed62cf4f6)

**Comment by sebastinas** [comment]
Fixed in 9c0017b4ddd086a695a8092db6affe06c687d6da.
