### ISSUE TITLE
crash when quitting before PDF rendering is complete

### ISSUE THREAD

**Issue by vinc17fr** [pwmt/zathura#656]
With zathura at least up to 0.5.8, when I quit (with 'q') quickly after starting it on a PDF file, zathura sometimes crashes (apparently before rendering is complete). This happens mostly with an old machine, probably because it is slower to render the PDF document. So I had the idea to try on larger PDF files, with large images, and I can reproduce the crash all the time.

It can be either a segmentation fault or an assertion failure in the cairo library, e.g.
```
zathura: ../../../src/cairo-pattern.c:1155: cairo_pattern_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)' failed.
zsh: IOT instruction (core dumped)  zathura wd/doc/lyon/tcl/lignes-fortes.pdf
```
and
```
zathura: ../../../src/cairo-pattern.c:1093: cairo_pattern_reference: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)' failed.
zsh: IOT instruction (core dumped)  zathura visorando-circuit-des-chapelles-a-sainte-catherine.pdf
```

According to the zathura source, zathura uses threading. So the cause might be that when zathura receives 'q', it starts to free some data structures while rendering is still done in another thread, which yields the crash.

Bug initially reported in the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1032609

**Comment by sebastinas** [comment]
This is essentially the same bug as #395.
