### ISSUE TITLE
Wrong page layout

### ISSUE THREAD

**Issue by Massimo-B** [pwmt/zathura#672]
I have a PDF-File that gets parts of the page cut because the page layout is wrong in Zathura. It shows some quadratic layout while the content actually is DIN-A4.
Plain mupdf and also evince are showing the file correctly.
I can't share because of private content, can I do anything to reproduce or debug the issue?

```
$ file file.pdf 
file: PDF document, version 1.3, 61 page(s)
```

I'm using zathura with zathura-pdf-mupdf on Gentoo:
```
app-text/zathura-0.5.4
app-text/zathura-pdf-mupdf-0.4.3
app-text/mupdf-1.24.1
app-text/evince-45.0
```

**Comment by sebastinas** [comment]
Fixed in 7fb21f32ba2d94cc3b85c6a67628849ef5b1a422.
