### ISSUE TITLE
; instead of : for opening inputbar with ":"

### ISSUE THREAD

**Issue by aljustiet** [pwmt/zathura#678]
I want to open the command bar without pressing the `shift+;`, but just `;`. I tried to map the `;` to `toggle_inputbar`, but it focuses the inputbar and not the inputbar with `:`.

**Comment by jdujava** [comment]
You can try
```
map ; feedkeys :
```

**Comment by aljustiet** [comment]
> You can try
> 
> ```
> map ; feedkeys :
> ```

Thanks I should've read the documentation more carefully. Hyprland has a similar feature called `pass`, and I searched for it in the zathurarc(5), but it didn't give any result.
