### ISSUE TITLE
[Bug]: 0.5.10 tag is missing

### ISSUE THREAD

**Issue by Antiz96** [pwmt/zathura#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

Hi,

The website reports [0.5.10](https://pwmt.org/news/zathura-0-5-10/index.html) as the latest version available, but the matching tag is missing from this repository. Currently the latest tag is 0.5.9.

(Sorry if it isn't the right place to raise this)

### Steps to reproduce

N/A

### Expected behavior

0.5.10 tag being available

### zathura version (zathura --version)

N/A

### girara version (zathura --version)

N/A

### zathura backend

N/A

**Comment by sebastinas** [comment]
Pushed.
