### ISSUE TITLE
Some information after a session is completed

### ISSUE THREAD

**Issue by davudMagomedov** [pwmt/zathura#703]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem

Hi, sorry for my probably bad English.

It would be very helpful for me if zathura showed the page number I stopped at after session (of course through some flag).

There may be flag `--show-page-number` for example, or special option in `zathurarc`.

### Expected behavior

```
$ zathura somebook.pdf --show-page-number
<session>
<stopped at page 431 and exited>
431
$ |
```

**Comment by sebastinas** [comment]
You can get the information via both the dbus interface and via the fileinfo database. I don't think that this is a good addition to zathura itself.
