### ISSUE TITLE
[Bug]: Only show part of rotated page

### ISSUE THREAD

**Issue by a44881212** [pwmt/zathura#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

The following image is normal display of the rotated page (opened with inkscape).
![normal](https://github.com/user-attachments/assets/74d4a173-ac50-4a9c-9c67-2c088a798989)
I opened the same file with Zathura but got the following abnormal displays (only show northwest of contents).
![abnormal_1](https://github.com/user-attachments/assets/cfdccd3f-7027-4dbf-945a-e7a9afcb8062)
![abnormal_2](https://github.com/user-attachments/assets/26cd3bf1-b040-453b-a1ea-da6bf21524d3)

I think the problem might be the page is scaled to the same width of other page but the contents are not.

### Steps to reproduce

Open a pdf file which contains some rotated pages.

### Expected behavior

Show all of contents in the rotated page.

### zathura version (zathura --version)

zathura 0.5.8

### girara version (zathura --version)

girara 0.4.4 (runtime: 0.4.4)

### zathura backend

(plugin) pdf-mupdf (0.4.4) (/usr/lib64/zathura/libpdf-mupdf.so)

**Comment by sebastinas** [comment]
This is fixed in zathura 0.5.10.
