### ISSUE TITLE
Synctex Highlights stack, completely obscure text

### ISSUE THREAD

**Issue by sebastinas** [pwmt/zathura#71]
*On GitLab by @max-te on Jul 30, 2018, 16:21*

---

I am using zathura as a viewer with LaTeXTools for Sublime Text.
Lines highlighted via synctex seem to be highlighted to varying degrees of opacity. Sometimes this can lead to completely unreadable text as seen here:
![image](https://git.pwmt.org/pwmt/zathura/uploads/3b0c215e424eac92292a667c3557246f/image.png)

`set highlight-transparency 0.05` alleviates this a bit, but leads to the highlighting being barely visible in other sections.

**Comment by sebastinas** [comment]
*On GitLab by @dwap on Nov 8, 2019, 09:47*

---

Same problem here, can be very annoying when using sync. I am wondering: is it really a zathura problem, or is just zathura being called with multiple overlapping highlight areas? Is there any workaround? Reducing the transparency as mentioned is not really a solution, but maybe there is a way to just draw the borders of the rectangle somehow rather than playing with the highlight color? I don't see anything related in the config though.

**Comment by sebastinas** [comment]
Fixed thanks to https://github.com/pwmt/zathura/pull/36

**Comment by sebastinas** [comment]
closed

**Comment by BachoSeven** [comment]
@sebastinas I'm currently experiencing this same problem with both normal search highlight and Synctex, on Zathura 0.5.5 with zathura-pdf-mupdf 0.4.1 on Arch Linux (but it's been happening for a few months) with DWM. I've tried de-activating `picom` but the compositor doesn't seem to have anything to do with it.

Any clues as to why it is happening?

**Comment by BachoSeven** [comment]
I think I got it, something must've changed in a (relatively) recent version regarding the configuration of the search highlight colors (`highlight-color` and `highlight-active-color`), I had them set to a simple HEX value while the default seems to be RGBA with 0.5 transparency. 

I guess perhaps the fallback alpha value in this case shouldn't be 1 though(?)

**Comment by dmadisetti** [comment]
I've been having this issue for 1-2 months now, but the default seems to work strangely.

**Comment by dmadisetti** [comment]
Cool, https://github.com/pwmt/zathura/commit/fb2b5da84b7f6b0c003ea58edbdb1c2524ab387e

Transparency is defined on the highlight now. For transparency, must be in rgba format. e.g.

```
set highlight-active-color      rgba(0,188,0,0.5)
```
